### ISSUE TITLE
On Calendar TypeError: jQuery(...).select2 is not a function

### ISSUE THREAD

**Issue by Y2KWebs** [projectknife/Projectfork#1640]
Hello,
We are working on Joomla 3.0 and Projectfork 4.3.2 and we have this error on calendar
TypeError: jQuery(...).select2 is not a function

We try some solutions suggested in the post, but without success, we only have K2 installed, so theres no other components that can affect it, could you please help us
![sin-titulo-2](https://cloud.githubusercontent.com/assets/12713670/8603787/9aef52ca-2637-11e5-9c71-eddf3f612f7f.jpg)
